export interface ClientData {
  src: string;
  alt: string;
  className?: string;
  show?: boolean;
  href?: string;
  clientType: "national" | "international";
  websiteImgUrl?:string;
}

export interface ChooseCardProsData {
  title: string;
  subtitle: string;
  Icon: React.ReactNode;
}

export const ClientImages: ClientData[] = [
  {
    src: "/clientsLogo/ALLURE-NAINITAL-LOGO.png",
    alt: "Client1",
    className: "#000000",
    show: true,
    clientType: "national",
  },
  {
    src: "/clientsLogo/Client2.png",
    alt: "Client2",
    className: "#ffffff",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Client3.png",
    alt: "Client3",
    className: "#ffffff",
    href: "https://marriott-hotels.marriott.com/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/BG-logo.jpg",
    alt: "Client4",
    className: "#ffffff",
    href: "https://www.bhairahawagardenresort.com/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/BURKEY-BLACK-LOGO-01.png",
    alt: "Client5",
    className: "#ffffff",
    show: false,
    clientType: "national",
  },
  {
    src: "/clientsLogo/Client6.png",
    alt: "Client6",
    className: "#ffffff",
    href: "https://www.goldentulip.com/en-us/?sr=SEO_GOOGLE",
    clientType: "international",
  },
  {
    src: "/clientsLogo/DOUBLE-TREE-LOGO-01.png",
    alt: "Client8",
    className: "#ffffff",
    href: "https://www.hilton.com/en/brands/doubletree-by-hilton/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Dunagiri-Logo-Square.png",
    alt: "Client9",
    className: "#ffffff",
    href: "https://www.dunagiri.com/",
    clientType: "national",
  },
  // {
  //   src: Client10,
  //   alt: "Client10",
  // },
  {
    src: "/clientsLogo/Hyatt-regency-logo.jpg",
    alt: "Client11",
    className: "#ffffff",
    href: "https://www.hyatt.com/hyatt-regency/en-US",
    clientType: "international",
  },
  {
    src: "/clientsLogo/JW-Mariott-logo.png",
    alt: "Client12",
    className: "#ffffff",
    href: "https://jw-marriott.marriott.com/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Novotel-Logo.png",
    alt: "Client13",
    className: "#ffffff",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Radisson-Logo.png",
    alt: "Radisson",
    className: "#ffffff",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Ramada-Logo.jpg",
    alt: "Client15",
    className: "#ffffff",
    href: "https://www.wyndhamhotels.com/ramada",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Taj-hotel-logo.png",
    alt: "Client16",
    className: "#ffffff",
    href: "https://www.tajhotels.com/en-in",
    clientType: "national",
  },
  // {
  //   src: Client17,
  //   alt: "Client17",
  // },
  {
    src: "/clientsLogo/peace@peak.png",
    alt: "Client18",
    className: "#f7f7f7",
    clientType: "national",
  },
  {
    src: "/clientsLogo/logo_uv-removebg-preview-e1701685619775.webp",
    alt: "Client19",
    show: false,
    className: "#ffffff",
    href: "https://www.urbanvenue.in/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/bunker-house.jpg",
    alt: "Client20",
    className: "#f7f7f7",
    show: false,
    href: "https://thebunkerhouse.in/",
    websiteImgUrl:"/website/bunker-house.png",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Red-Rock-villa.jpg",
    alt: "Client21",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/wabi-sabi.jpg",
    alt: "Client22",
    className: "#f7f7f7",
    href: "https://wabisabiresorts.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/ebc.jpg",
    alt: "Client23",
    className: "#1f1f1f",
    href: "https://www.ebcmussoorie.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Riviera.jpg",
    alt: "Client24",
    className: "#f7f7f7",
    href: "https://www.rivieraresortrishikesh.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/footerspicelogo.png",
    alt: "Client25",
    className: "#21413e",
    show: false,
    clientType: "international",
  },
  {
    src: "/clientsLogo/chefkenzo.png",
    alt: "Client26",
    show: false,
    className: "#ffffff",
    href: "https://kenzok.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/eracamp.png",
    alt: "Client27",
    className: "#e6e6e6",
    href: "https://eracamps.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Grandview_resort.jpg",
    alt: "Client28",
    className: "#f3f3f3",
    clientType: "national",
  },
  {
    src: "/clientsLogo/468F.png",
    alt: "Client29",
    show: false,
    className: "#ffffff",
    href: "https://468f.ca/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/Aaoji.png",
    alt: "Client30",
    className: "#000000",
    show: false,
    href: "https://www.aaojirestaurant.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/STERNWHEELER.png",
    alt: "Client31",
    className: "#ffffff",
    clientType: "international",
    href: "https://sternwheeler.com/",
  },
  {
    src: "/clientsLogo/Season-suites.png",
    alt: "Client32",
    className: "#ffffff",
    href: "https://www.seasonssuites.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/emeraldtrail.png",
    alt: "Client33",
    href: "https://www.emeraldtrail.in/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/kiyostay.png",
    alt: "Client34",
    className: "#ffffff",
    href: "https://kiyostays.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/lakehill.png",
    alt: "Client35",
    href: "https://thelakehill.com/",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/maati.png",
    alt: "Client36",
    className: "#000000",
    clientType: "national",
  },
  {
    src: "/clientsLogo/sprav.jpg",
    alt: "Client37",
    className: "#000000",
    href: "https://www.sparvhospitality.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Park Cafe.png",
    alt: "Client38",
    className: "#ffffff",
    show: false,
    clientType: "national",
  },
  {
    src: "/clientsLogo/deuropa.png",
    alt: "Client39",
    className: "#ffffff",
    href: "https://granddeeurope.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/dhruvees.png",
    alt: "Client40",
    className: "#000000",
    show: false,
    href: "https://www.dhruvees.com/home/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/hilton.png",
    alt: "Client42",
    className: "#ffffff",
    href: "https://www.hilton.com/en/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/hotel-platinum-shravasti.png",
    alt: "Client43",
    className: "#ffffff",
    href: "https://hotelplatinumshravasti.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/mahabir-palace.png",
    alt: "mahabir-palace",
    className: "#fff",
    href: "https://www.mahabirpalace.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/oak-climbing.png",
    alt: "Client45",
    className: "#007a39",
    href: "https://oakclimbingresort.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/tents&trails.png",
    alt: "Client47",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/minimalist.png",
    alt: "Client48",
    className: "#ffffff",
    href: "https://minimalisthotels.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/magnolia.png",
    alt: "Client49",
    className: "#000000",
    clientType: "national",
  },
  {
    src: "/clientsLogo/white-ridge.png",
    alt: "Client50",
    className: "#ffffff",
    href: "https://www.whiteridgehotel.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/avr.jpg",
    alt: "Client51",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/tulipInn.png",
    alt: "Client52",
    className: "#ffffff",
    href: "https://hotelgreencastle.com/tulip-inn-green-castle-mussoorie.html",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Hotel-Green-Castle.jpg",
    alt: "Client53",
    className: "#ffffff",
    href: "https://hotelgreencastle.com/hotel-green-castle.html",
    clientType: "national",
  },
  {
    src: "/clientsLogo/aqua-dunhinda.jpg",
    alt: "Client54",
    className: "#ffffff",
    href: "https://www.aquadunhinda.com/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/shreeiyengar.png",
    alt: "Client55",
    className: "#ffffff",
    show: false,
    href: "https://shreeiyengarfoods.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/kamalfarms.png",
    alt: "Client56",
    className: "#ffffff",
    href: "https://kamalfarms.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/petal-panyaram.png",
    alt: "Client57",
    show: false,
    className: "#15533c",
    href: "https://petalandpaniyaram.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/7Mile.png",
    alt: "Client58",
    show: false,
    className: "#ffffff",
    href: "https://7milebar.com.au/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/The-Jharna.png",
    alt: "Client59",
    clientType: "national",
  },
  {
    src: "/clientsLogo/chocolate-room.png",
    alt: "Client60",
    show: false,
    className: "#ffffff",
    href: "https://www.thechocolateroomindia.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/kumaon-bliss.jpg",
    alt: "Client62",
    className: "#faf1ea",
    clientType: "national",
  },
  {
    src: "/clientsLogo/ta.webp",
    alt: "Client63",
    className: "#ffffff",
    show: false,
    href: "https://www.tailgaterstx.com/",
    clientType: "international",
  },
  {
    src: "/clientsLogo/outer-ring.png",
    alt: "Client64",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/luxuryvibes.jpg",
    alt: "Client65",
    className: "#1e1e1e",
    href: "https://luxuryvibesstay.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Mango_grove_Logo.avif",
    alt: "Client66",
    className: "#FFCD62",
    href: "https://www.mangogrovehotel.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/naturoville.png",
    alt: "Client67",
    className: "#ffffff",
    href: "https://www.naturovillewellness.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/maira.jpeg",
    alt: "Client68",
    className: "#ffffff",
    href: "https://www.mairaresort.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/campton.png",
    alt: "Client69",
    clientType: "national",
  },
  {
    src: "/clientsLogo/ahistay-logo.png",
    alt: "Client70",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/muktkeshi-logo.png",
    alt: "Client71",
    href: "https://www.muktkeshii.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/MIRAMAR-logo.jpg",
    alt: "Client72",
    className: "#ffffff",
    clientType: "international",
  },
  {
    src: "/clientsLogo/nature-on-the-rocks.webp",
    alt: "Client73",
    href: "https://natureontherocks.in/",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/one-off.png",
    alt: "Client74",
    className: "#FBF6E3",
    href: "https://oneoffhotels.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/AravatLogo.png",
    alt: "Client75",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/opera-house.png",
    alt: "Client76",
    className: "#B39C4D",
    href: "https://operahouselonavala.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/colonels-resort.png",
    alt: "Client77",
    className: "#2F4B26",
    href: "https://www.colonelsresort.com/index.html",
    clientType: "national",
  },
  {
    src: "/clientsLogo/umaid2.png",
    alt: "Client78",
    href: "https://www.umaidpalace.com/",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/Manali-se.png",
    alt: "Client79",
    href: "https://manali-se.com/",
    className: "#2b3380",
    clientType: "national",
  },
  {
    src: "/clientsLogo/soni-arena-hotel.png",
    alt: "Client80",
    className: "#273342",
    href: "https://soniarenahotel.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/surbag.png",
    alt: "Client81",
    className: "#ffffff",
    href: "https://www.suryabagh.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/soul-stories.png",
    alt: "Client82",
    className: "#ffffff",
    href: "https://soulstorries.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/ZionHotel.png",
    alt: "Client83",
    className: "#ffffff",
    href: "https://www.thezionhotel.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/altin-stays.webp",
    alt: "Altin Stays",
    className: "#000000",
    href: "https://altinstays.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/anandha inn.webp",
    alt: "Anandha Inn",
    className: "#af1e28",
    href: "https://www.anandhainn.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/DLSM.webp",
    alt: "DLSM",
    className: "#000000",
    href: "",
    clientType: "international",
  },
  {
    src: "/clientsLogo/hotel-awadha-vilas.webp",
    alt: "Hotel Awadha Vilas",
    className: "#f7f7f7",
    href: "https://www.hotelawadhvilasayodhya.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/infinity.webp",
    alt: "Infinity",
    className: "#ffffff",
    href: "",
    clientType: "national",
  },
  {
    src: "/clientsLogo/la-mount.webp",
    alt: "La Mount",
    className: "#ffffff",
    href: "https://lamountladakh.in/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/lumi-logo.jpg",
    alt: "Lumi",
    className: "#ffffff",
    href: "",
    clientType: "national",
  },
  {
    src: "/clientsLogo/moets-water.png",
    alt: "Moets Water",
    className: "#ffffff",
    href: "https://waterfrontestatebymoets.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/moets.webp",
    alt: "Moets",
    className: "#ffffff",
    href: "",
    clientType: "national",
  },
  {
    src: "/clientsLogo/nothern-nawab.webp",
    alt: "Northern Nawab",
    className: "#ffffff",
    href: "https://www.northernnawab.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/revtree.webp",
    alt: "Revtree",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/stone-hedge.webp",
    alt: "Stone Hedge",
    className: "#ffffff",
    clientType: "national",
  },
  {
    src: "/clientsLogo/arkaya.png",
    alt: "arkaya",
    className: "#ffffff",
    href: "",
    clientType: "national",
  },
  {
    src: "/clientsLogo/corbett-the-grand.png",
    alt: "corbett-the-grand",
    className: "#ffffff",
    href: "https://www.corbettthegrand.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/naad-wellness.png",
    alt: "naad-wellness",
    className: "#7B584F",
    href: "https://naadwellness.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/north-wind.png",
    alt: "north-wind",
    className: "#1b1b1be6",
    href: "https://www.northwind57bir.com/",
    clientType: "national",
  },
  {
    src: "/clientsLogo/masti.webp",
    alt: "masti",
    className: "#1b1b1b",
    clientType: "international",
  },
  {
    src: "/clientsLogo/eastrenspice.webp",
    alt: "eastrenspice",
    className: "#ffffff",
    clientType: "international",
  },
];
